[[redirects]]
  from = "/xhttp"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[[redirects]]
  from = "/xhttp/*"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true
